image: rust:latest

stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - target/
    - .cargo/bin/
    - .cargo/registry/index/
    - .cargo/registry/cache/
    - .cargo/git/db/

build:
  stage: build
  script:
    - cargo build --release

test:
  stage: test
  script:
    - cargo run --release -- SOM/TestSuite/TestHarness.som
